baseURL = "https://stevelengui.github.io/"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
publishDir = "docs"

[languages]
  [languages.fr]
    languageName = "Français"
    title = "Steve Lengui - Doctorant en IA Neuromorphique"
    weight = 1
  [languages.en]
    languageName = "English"
    title = "Steve Lengui - PhD in Neuromorphic AI"
    weight = 2

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 301

theme = "ananke"

[params]
  description = "Site personnel de Steve Lengui, doctorant en IA neuromorphique pour IoT."
  author = "Steve Lengui"
  github = "https://github.com/stevelengui"
  linkedin = "https://linkedin.com/in/stevelengui"

# Menu principal pour le français
[[languages.fr.menu.main]]
  name = "Accueil"
  url = "/fr/"
  weight = 1

[[languages.fr.menu.main]]
  name = "À propos"
  url = "/fr/about/"
  weight = 2

[[languages.fr.menu.main]]
  name = "Services"
  url = "/fr/services/"
  weight = 3

[[languages.fr.menu.main]]
  name = "Publications"
  url = "/fr/publications/"
  weight = 4

[[languages.fr.menu.main]]
  name = "Blog"
  url = "/fr/blog/"
  weight = 5

[[languages.fr.menu.main]]
  name = "Projets"
  url = "/fr/projects/"
  weight = 6

[[languages.fr.menu.main]]
  name = "Contact"
  url = "/fr/contact/"
  weight = 7

# Menu principal pour l'anglais
[[languages.en.menu.main]]
  name = "Home"
  url = "/en/"
  weight = 1

[[languages.en.menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 2

[[languages.en.menu.main]]
  name = "Services"
  url = "/en/services/"
  weight = 3

[[languages.en.menu.main]]
  name = "Publications"
  url = "/en/publications/"
  weight = 4

[[languages.en.menu.main]]
  name = "Blog"
  url = "/en/blog/"
  weight = 5

[[languages.en.menu.main]]
  name = "Projects"
  url = "/en/projects/"
  weight = 6

[[languages.en.menu.main]]
  name = "Contact"
  url = "/en/contact/"
  weight = 7
